метод getAllTicket
misiekolbasie/support-service pull request #3
Opened 2021-04-06 19:43 UTC by misiekolbasie

сделал метод getAllTickets

2021-04-06 20:03 UTC, misiekolbasie commented
в методе GetTicketsByUserId нужно взять коллекцию пользователей, найти пользователя по id и селектом выбрать все тикеты созданные им(с его ID).

2021-04-06 20:09 UTC, DeployChef approved these changes
Посмотри первое ревью твое

2021-04-06 20:09 UTC, DeployChef commented on SupportService.DataAccess/Repositories/Interfaces/ITicketRepository.cs
> +
Пустая строка, надо бы убрать

2021-04-06 20:09 UTC, DeployChef commented on SupportService.DataAccess/Repositories/TicketRepository.cs
> +            var ticketss = new List<Ticket>();
Это не используется, можно закомментировать если тебе еще это нужно

2021-04-06 20:09 UTC, DeployChef commented on SupportService/Services/Interfaces/ITicketService.cs
> +        int CreateTicket(CreateTicketRequest createTicketRequest);
а тут отступ бы добавить, методы через отступы красиво выглядят

2021-04-06 20:15 UTC, DeployChef requested changes

2021-04-06 20:15 UTC, DeployChef commented on SupportService.DataAccess/Repositories/Interfaces/ITicketRepository.cs
> +using System.Collections.Generic;
Попытка запроса апрува

2021-04-07 07:05 UTC, misiekolbasie commented on SupportService.DataAccess/Repositories/Interfaces/ITicketRepository.cs
> +
сделал

2021-04-07 07:05 UTC, misiekolbasie commented on SupportService.DataAccess/Repositories/TicketRepository.cs
> +            var ticketss = new List<Ticket>();
сделал

2021-04-07 07:05 UTC, misiekolbasie commented on SupportService/Services/Interfaces/ITicketService.cs
> +        int CreateTicket(CreateTicketRequest createTicketRequest);
сделал

2021-04-07 11:40 UTC, DeployChef requested changes

2021-04-07 11:40 UTC, DeployChef commented on SupportService/Controllers/TicketsController.cs
> +        public async Task<IActionResult> GetTicket() // Смотреть все тикеты
Зачем переименовал? мы запрашиваем все тикеты а не один тикет

2021-04-07 11:40 UTC, DeployChef commented on SupportService/Services/Interfaces/ITicketService.cs
> +        IEnumerable<Ticket> GetTickets();
Тут отступ

2021-04-07 11:40 UTC, DeployChef commented on SupportService.DataAccess/Repositories/TicketRepository.cs
> +                    if (_usersDB.Any(c => c.Value.Id == id.Value.AutorId))
Ты сделал лютую дичь
Параметр Id юзера прилетает тебе в контроллере, используй его. 
Вот тут тут добавил юзер дб, она же пуста, да и репа тикетов вообще не работает с юзерами, да и вообще какой то бред сделал.

2021-04-07 11:40 UTC, DeployChef commented on SupportService.DataAccess/Repositories/TicketRepository.cs
> +             foreach (var id in _ticketsDb)
foreach (var id in _ticketsDb) - это не id ты пикаешь, а пары хоспаде, ПАРЫ - переменная типа Pair<int, Ticket>()
Это значит что там ПАРА ключ и значение. а не просто id

2021-04-07 11:40 UTC, DeployChef commented on SupportService/Controllers/TicketsController.cs
>          public async Task<IActionResult> GetTicketsByUserId(int userId) // Просмотр тикетов пользователя
public async Task<IActionResult> GetTicketsByUserId(int userId)  
мы написали запрос, в запросе приходит id пользователя по которому надо найти тикеты.
у тебя есть все данные по поиску в самом запросе. используй userId

2021-04-07 11:43 UTC, DeployChef commented on SupportService.DataAccess/Repositories/TicketRepository.cs
> +             foreach (var id in _ticketsDb)
БУКВАЛЬНО foreach (var id in _ticketsDb) = ПЕРЕЧИСЛИ ВСЕ ПАРЫ ИЗ ТИКЕТС ДБ
ФОРИЧ ПО ОЧЕРЕДИ ВОЗЬМЕТ ПАРЫ И ПОЛОЖИТ В ПЕРЕМЕННУЮ, ПРОГОНИТ ЦИКЛ И ВОЗЬМЕТ ДРУГУЮ ПАРУ

2021-04-08 19:36 UTC, misiekolbasie commented on SupportService.DataAccess/Repositories/TicketRepository.cs
> +                        ticketsByUserId.Add(id);
повар, сделал метод, при добавлении результатов в лист пишет ошибку CS1503

2021-04-08 19:39 UTC, merged